package com.tuitanews.persistence;

import com.tuitanews.domain.ApiChannel;
import com.tuitanews.domain.ApiChannelExample;
import java.util.List;

public interface ApiChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int countByExample(ApiChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int insert(ApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int insertSelective(ApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    List<ApiChannel> selectByExample(ApiChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    ApiChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int updateByPrimaryKeySelective(ApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int updateByPrimaryKey(ApiChannel record);
}