package com.tuitanews.persistence;

import com.tuitanews.domain.NewsApiChannel;
import com.tuitanews.domain.NewsApiChannelExample;
import java.util.List;

public interface NewsApiChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int countByExample(NewsApiChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int insert(NewsApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int insertSelective(NewsApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    List<NewsApiChannel> selectByExample(NewsApiChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    NewsApiChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int updateByPrimaryKeySelective(NewsApiChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    int updateByPrimaryKey(NewsApiChannel record);
}