package com.tuitanews.domain;

import java.util.Date;

public class NewsBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.nid
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.title
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.content
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.content_with_imgs
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String contentWithImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.source
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.html
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.face_url
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String faceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.desc
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.channel_id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.channel_name
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.link
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.imageurls
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String imageurls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.pub_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private String pubDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_bean.create_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.id
     *
     * @return the value of news_bean.id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.id
     *
     * @param id the value for news_bean.id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.nid
     *
     * @return the value of news_bean.nid
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.nid
     *
     * @param nid the value for news_bean.nid
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setNid(String nid) {
        this.nid = nid == null ? null : nid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.title
     *
     * @return the value of news_bean.title
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.title
     *
     * @param title the value for news_bean.title
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.content
     *
     * @return the value of news_bean.content
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.content
     *
     * @param content the value for news_bean.content
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.content_with_imgs
     *
     * @return the value of news_bean.content_with_imgs
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getContentWithImgs() {
        return contentWithImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.content_with_imgs
     *
     * @param contentWithImgs the value for news_bean.content_with_imgs
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setContentWithImgs(String contentWithImgs) {
        this.contentWithImgs = contentWithImgs == null ? null : contentWithImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.source
     *
     * @return the value of news_bean.source
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.source
     *
     * @param source the value for news_bean.source
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.html
     *
     * @return the value of news_bean.html
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.html
     *
     * @param html the value for news_bean.html
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.face_url
     *
     * @return the value of news_bean.face_url
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getFaceUrl() {
        return faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.face_url
     *
     * @param faceUrl the value for news_bean.face_url
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setFaceUrl(String faceUrl) {
        this.faceUrl = faceUrl == null ? null : faceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.desc
     *
     * @return the value of news_bean.desc
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.desc
     *
     * @param desc the value for news_bean.desc
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.channel_id
     *
     * @return the value of news_bean.channel_id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.channel_id
     *
     * @param channelId the value for news_bean.channel_id
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.channel_name
     *
     * @return the value of news_bean.channel_name
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.channel_name
     *
     * @param channelName the value for news_bean.channel_name
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.link
     *
     * @return the value of news_bean.link
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.link
     *
     * @param link the value for news_bean.link
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.imageurls
     *
     * @return the value of news_bean.imageurls
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getImageurls() {
        return imageurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.imageurls
     *
     * @param imageurls the value for news_bean.imageurls
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setImageurls(String imageurls) {
        this.imageurls = imageurls == null ? null : imageurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.pub_date
     *
     * @return the value of news_bean.pub_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.pub_date
     *
     * @param pubDate the value for news_bean.pub_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_bean.create_date
     *
     * @return the value of news_bean.create_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_bean.create_date
     *
     * @param createDate the value for news_bean.create_date
     *
     * @mbggenerated Tue Aug 30 17:14:03 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}