package com.tuitanews.domain;

import java.util.Date;

public class NewsApiChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_api_channel.id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_api_channel.api_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    private String apiChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_api_channel.news_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    private Integer newsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_api_channel.create_date
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_api_channel.status
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_api_channel.id
     *
     * @return the value of news_api_channel.id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_api_channel.id
     *
     * @param id the value for news_api_channel.id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_api_channel.api_channel_id
     *
     * @return the value of news_api_channel.api_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public String getApiChannelId() {
        return apiChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_api_channel.api_channel_id
     *
     * @param apiChannelId the value for news_api_channel.api_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setApiChannelId(String apiChannelId) {
        this.apiChannelId = apiChannelId == null ? null : apiChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_api_channel.news_channel_id
     *
     * @return the value of news_api_channel.news_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Integer getNewsChannelId() {
        return newsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_api_channel.news_channel_id
     *
     * @param newsChannelId the value for news_api_channel.news_channel_id
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setNewsChannelId(Integer newsChannelId) {
        this.newsChannelId = newsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_api_channel.create_date
     *
     * @return the value of news_api_channel.create_date
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_api_channel.create_date
     *
     * @param createDate the value for news_api_channel.create_date
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_api_channel.status
     *
     * @return the value of news_api_channel.status
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_api_channel.status
     *
     * @param status the value for news_api_channel.status
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}