package com.tuitanews.domain;

import java.util.Date;

public class NewsChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_channel.id
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_channel.name
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_channel.create_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_channel.update_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_channel.status
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_channel.id
     *
     * @return the value of news_channel.id
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_channel.id
     *
     * @param id the value for news_channel.id
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_channel.name
     *
     * @return the value of news_channel.name
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_channel.name
     *
     * @param name the value for news_channel.name
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_channel.create_date
     *
     * @return the value of news_channel.create_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_channel.create_date
     *
     * @param createDate the value for news_channel.create_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_channel.update_date
     *
     * @return the value of news_channel.update_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_channel.update_date
     *
     * @param updateDate the value for news_channel.update_date
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_channel.status
     *
     * @return the value of news_channel.status
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_channel.status
     *
     * @param status the value for news_channel.status
     *
     * @mbggenerated Thu Aug 25 17:31:05 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}