package com.tuitanews.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewsApiChannelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public NewsApiChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdIsNull() {
            addCriterion("api_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdIsNotNull() {
            addCriterion("api_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdEqualTo(String value) {
            addCriterion("api_channel_id =", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdNotEqualTo(String value) {
            addCriterion("api_channel_id <>", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdGreaterThan(String value) {
            addCriterion("api_channel_id >", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("api_channel_id >=", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdLessThan(String value) {
            addCriterion("api_channel_id <", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdLessThanOrEqualTo(String value) {
            addCriterion("api_channel_id <=", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdLike(String value) {
            addCriterion("api_channel_id like", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdNotLike(String value) {
            addCriterion("api_channel_id not like", value, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdIn(List<String> values) {
            addCriterion("api_channel_id in", values, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdNotIn(List<String> values) {
            addCriterion("api_channel_id not in", values, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdBetween(String value1, String value2) {
            addCriterion("api_channel_id between", value1, value2, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andApiChannelIdNotBetween(String value1, String value2) {
            addCriterion("api_channel_id not between", value1, value2, "apiChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdIsNull() {
            addCriterion("news_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdIsNotNull() {
            addCriterion("news_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdEqualTo(Integer value) {
            addCriterion("news_channel_id =", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdNotEqualTo(Integer value) {
            addCriterion("news_channel_id <>", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdGreaterThan(Integer value) {
            addCriterion("news_channel_id >", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_channel_id >=", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdLessThan(Integer value) {
            addCriterion("news_channel_id <", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_channel_id <=", value, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdIn(List<Integer> values) {
            addCriterion("news_channel_id in", values, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdNotIn(List<Integer> values) {
            addCriterion("news_channel_id not in", values, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("news_channel_id between", value1, value2, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andNewsChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_channel_id not between", value1, value2, "newsChannelId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_api_channel
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 27 14:43:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_api_channel
     *
     * @mbggenerated Sat Aug 27 14:43:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}